spring:
  application:
    name: auth-server

  security:
    oauth2:
      authorizationserver:
        issuer: ${JWT_ISSUER:http://localhost:9000}

jwt:
  private-key: ${JWT_PRIVATE_KEY:classpath:keys/private-key.pem}
  public-key: ${JWT_PUBLIC_KEY:classpath:keys/public-key.pem}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      show-details: always

app:
  metamask:
    nonce-expiration-minutes: 5
    signature-message-prefix: "Sign this message to authenticate: "

user:
  uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}