spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:9000}
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:9000}/oauth2/jwks
      client:
        id: ${OAUTH_CLIENT_ID:authentification-service-client}
        secret: ${OAUTH_CLIENT_SECRET:authentification-service-secret}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        # ------------------------ AUTH SERVER ROUTES ------------------------
        - id: auth-nonce-route
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/metamask/nonce
            - Method=GET
          filters:
            - StripPrefix=0

        - id: auth-login-route
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/metamask/login
            - Method=POST
          filters:
            - StripPrefix=0

        - id: auth-refresh-route
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/metamask/refresh
            - Method=POST
          filters:
            - StripPrefix=0

        - id: auth-server-public
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/oauth2/**

        # ------------------------ USER SERVICE ROUTES ------------------------
        - id: user-register
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - TokenRelay

        - id: user-service
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users/**,/api/users
          filters:
            - TokenRelay

        # ------------------------ RENTAL AGREEMENT ------------------------
        - id: RentalAgreement-microservice
          uri: ${RENTAL-AGREEMENT-URL:http://localhost:8083}
          predicates:
            - Path=/api/rentalAgreement-microservice/**
          filters:
            - TokenRelay

        # ------------------------ PROPERTY MICROSERVICE ------------------------
        - id: property-microservice
          uri: ${PROPERTY-MICROSERVICE-URL:http://localhost:8084}
          predicates:
            - Path=/api/property-microservice/**
          filters:
            - TokenRelay

      # ------------------------ CORS ------------------------
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Type
              - X-Total-Count
            allowCredentials: true
            maxAge: 3600

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    root: DEBUG

# ==================================================================
#                    SPRING SECURITY ACCESS RULES
# ==================================================================
security:
  filter:
    chains:

      # ------ PUBLIC GET ROUTES FOR PROPERTY MICROSERVICE ------
      - pattern: /api/property-microservice/properties/**
        http:
          securityMatcher: /api/property-microservice/properties/**
          authorizeHttpRequests:
            - pattern: /api/property-microservice/properties/**
              methods: GET
              access: permitAll
          oauth2:
            resourceServer:
              jwt: {}

      - pattern: /api/property-microservice/rooms/**
        http:
          securityMatcher: /api/property-microservice/rooms/**
          authorizeHttpRequests:
            - pattern: /api/property-microservice/rooms/**
              methods: GET
              access: permitAll
          oauth2:
            resourceServer:
              jwt: {}

      - pattern: /api/property-microservice/properties/room-images/**
        http:
          securityMatcher: /api/property-microservice/properties/room-images/**
          authorizeHttpRequests:
            - pattern: /api/property-microservice/properties/room-images/**
              methods: GET
              access: permitAll
          oauth2:
            resourceServer:
              jwt: {}

      # ------ DEFAULT RULE : TOUT LE RESTE REQUIERT JWT ------
      - pattern: /**
        http:
          securityMatcher: /**
          authorizeHttpRequests:
            - pattern: /**
              access: isAuthenticated
          oauth2:
            resourceServer:
              jwt: {}
