spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:9000}
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:9000}/oauth2/jwks
      client:
        id: ${OAUTH_CLIENT_ID:authentification-service-client}
        secret: ${OAUTH_CLIENT_SECRET:authentification-service-secret}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        # ------------------------ AUTH SERVER ROUTES ------------------------
        - id: auth-nonce-route
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/metamask/nonce
            - Method=GET
          filters:
            - StripPrefix=0

        - id: auth-login-route
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/metamask/login
            - Method=POST
          filters:
            - StripPrefix=0

        - id: auth-refresh-route
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/api/auth/metamask/refresh
            - Method=POST
          filters:
            - StripPrefix=0

        - id: auth-server-public
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/oauth2/**,/.well-known/**

        # ------------------------ USER SERVICE ROUTES ------------------------
        - id: user-register
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-wallet-public
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users/wallet/**
            - Method=GET

        - id: user-nonce
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users/nonce
            - Method=POST,DELETE,GET

        - id: user-list-protected
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users
            - Method=GET
          filters:
            - TokenRelay

            # Protected: update user
        - id: user-update-protected
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users/{id}
            - Method=PATCH
          filters:
            - TokenRelay

            # Protected: delete user
        - id: user-delete-protected
          uri: ${USER-MANAGEMENT-SERVICE-URL:http://localhost:8081}
          predicates:
            - Path=/api/users/{id}
            - Method=DELETE
          filters:
            - TokenRelay

        # ------------------------ RENTAL AGREEMENT ------------------------
        - id: rental-agreement-microservice
          uri: ${RENTAL-AGREEMENT-URL:http://localhost:8083}
          predicates:
            - Path=/api/rentalAgreement-microservice/**
          filters:
            - TokenRelay

        # ------------------------ PROPERTY MICROSERVICE ------------------------
        - id: property-microservice-get-public
          uri: ${PROPERTY-MICROSERVICE-URL:http://localhost:8084}
          predicates:
            - Path=/api/property-microservice/**
            - Method=GET

        - id: property-microservice-protected
          uri: ${PROPERTY-MICROSERVICE-URL:http://localhost:8084}
          predicates:
            - Path=/api/property-microservice/**
          filters:
            - TokenRelay

        # Notifications
        - id: notification-microservice
          uri: ${NOTIFICATION_MICROSERVICE_URL/ws-notifications}
          predicates:
            - Path=/api/notifications/**
          filters:
            - TokenRelay

            # WebSocket Notifications
        - id: notification-ws
          uri: ws://localhost:8085
          predicates:
            - Path=/ws-notifications/**
      # ------------------------ CORS ------------------------
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Type
              - X-Total-Count
            allowCredentials: true
            maxAge: 3600

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG