spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    root: DEBUG