spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:9000}
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:9000}/oauth2/jwks
      client:
        id: ${OAUTH_CLIENT_ID:authentification-service-client}
        secret: ${OAUTH_CLIENT_SECRET:authentification-service-secret}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        - id: auth-server-public
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/oauth2/**
            - /.well-known/**

        - id: auth-service-public
          uri: lb://AUTHENTIFICATION-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-register
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/users
          filters:
            - RemoveRequestHeader=Cookie


        - id: user-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - TokenRelay=

        - id: RentalAgreement-microservice
          uri: lb://RentalAgreement-microservice
          predicates:
             - Path=/api/v1/**

        - id: property-microservice
          uri: lb://PROPERTY-MICROSERVICE
          predicates:
            - Path=/api/property

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Type
              - X-Total-Count
            allowCredentials: true
            maxAge: 3600

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG
    root: DEBUG