spring:
  application:
    name: property-microservice



  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB



logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

application:
  security:
    jwt:
      secret-key: b7f9c2e4a1d84f76aa93f0e2c6b1a8d3f5e9c0ab12ff78dd3344ee77aa2299ff

# ==================================
# Web3j Configuration
# ==================================

contract:
  rental:
    address: 0x5FbDB2315678afecb367f032d93F642f64180aa3

wallet:
  private-key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d

# ==================================
# Supabase Configuration
# ==================================
supabase:
  dbpassword: wGW#6fLi&&TwRy5
  url: https://wzqnlcmmqqfqisqrshkp.supabase.co
  anon-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cW5sY21tcXFmcWlzcXJzaGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4NTU2OTQsImV4cCI6MjA3OTQzMTY5NH0.HGOZapCQ43Z7E4j2tAVPDdymyUfhzXiv-pgTVz-m4oY
  service_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cW5sY21tcXFmcWlzcXJzaGtwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mzg1NTY5NCwiZXhwIjoyMDc5NDMxNjk0fQ.ddljPbgZk_pw9W99D8cJq94Nby_qKtj7b39zkpEU13U
  storage:
    bucket-name: property-images-bucket


microservice:
  recommendation-ai:
    url: http://localhost:8001

userManagement:
  service:
    url: ${USER_MANAGEMENT_SERVICE_URL:http://localhost:8084}