server:
  port: 8080

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:9000}
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:9000}/oauth2/jwks

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      routes:
        - id: auth-server-public
          uri: ${AUTH_SERVER_URL:http://localhost:9000}
          predicates:
            - Path=/oauth2/**,/.well-known/**

        - id: auth-service-public
          uri: lb://AUTHENTIFICATION-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - TokenRelay=

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL:http://localhost:4200}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            exposedHeaders:
              - Authorization
              - Content-Type
              - X-Total-Count
            allowCredentials: true
            maxAge: 3600